name: "Make OpenWrt using flippy's script"
author: "https://github.com/ophub/flippy-openwrt-actions"
description: "Support Amlogic, Rockchip and Allwinner boxes."
inputs:
  mode:
    description: "Select script."
    required: false
    default: "flippy"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd ${{ github.action_path }}
        ./openwrt_flippy.sh

branding:
  icon: "terminal"
  color: "gray-dark"
